In [4]:
import numpy as np
import pandas as pd

In [36]:
# Create an array of size 10 filled with 0
x = np.array(['0' * 10])

In [37]:
type(x)

numpy.ndarray

In [38]:
print(x)

['0000000000']


In [30]:
# Set fifth value to 1 from above array
x[1]

IndexError: index 1 is out of bounds for axis 0 with size 1

In [52]:
# Crean an array with values ranging from 10 to 49
np.arange(10,50)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [51]:
# Create a 5*5 matrix with values ranging from 0 to 24
np.arange(0,25).reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [54]:
# Create a 5*5 identity matrix
np.eye(5)

array([[ 1.,  0.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.,  0.],
       [ 0.,  0.,  1.,  0.,  0.],
       [ 0.,  0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  0.,  1.]])

In [60]:
# Crean an 5*5 array with random values 
# and find the minimum and maximum value
y = np.random.rand(25)

In [61]:
y.max()

0.99402715723410096

In [63]:
y.min()

0.052037799959524622

In [69]:
# 4*3 matrix is filled with 1
a = np.ones(12).reshape(4,3)
# 3*2 matrix is filled with random number
b = np.random.rand(6).reshape(3,2)

In [73]:
# Multiply a 4*3 matrix by a 3*2 matrix
a.dot(b)

array([[ 0.57112588,  1.54453382],
       [ 0.57112588,  1.54453382],
       [ 0.57112588,  1.54453382],
       [ 0.57112588,  1.54453382]])

In [74]:
# Transpose ablove matrix
a.dot(b).T

array([[ 0.57112588,  0.57112588,  0.57112588,  0.57112588],
       [ 1.54453382,  1.54453382,  1.54453382,  1.54453382]])

In [76]:
# Create two matrices ranging from 0 to 24 and 25 to 49
c = np.arange(0,25).reshape(5,5)
d = np.arange(25,50).reshape(5,5)

In [81]:
# Add two matrix
c + d

array([[25, 27, 29, 31, 33],
       [35, 37, 39, 41, 43],
       [45, 47, 49, 51, 53],
       [55, 57, 59, 61, 63],
       [65, 67, 69, 71, 73]])

In [82]:
c - d

array([[-25, -25, -25, -25, -25],
       [-25, -25, -25, -25, -25],
       [-25, -25, -25, -25, -25],
       [-25, -25, -25, -25, -25],
       [-25, -25, -25, -25, -25]])

In [161]:
import pandas as pd
import numpy as np
exam_data = {'name': ['Anastasia','Catherine','Cahill','James','Emily','Michael','Monica','Laura','Kevin','Jordan'],
            'score': [13,9.5,16.5,np.nan, 11,20,17, np.nan, 8.5, 19],
            'attempts': [1,3,3,2,2,3,2,3,2,1],
            'qualify': ['yes','no','yes','no','no','yes','yes','no','no','yes']}
labels = ['a','b','c','d','e','f','g','h','i','j']
df = pd.DataFrame(exam_data, index = labels)

In [162]:
df

attempts       name qualify  score
a         1  Anastasia     yes   13.0
b         3  Catherine      no    9.5
c         3     Cahill     yes   16.5
d         2      James      no    NaN
e         2      Emily      no   11.0
f         3    Michael     yes   20.0
g         2     Monica     yes   17.0
h         3      Laura      no    NaN
i         2      Kevin      no    8.5
j         1     Jordan     yes   19.0

In [163]:
# Select the 'name', and 'score' columns from the above DataFrame
df.loc[:,['name','score']]

name  score
a  Anastasia   13.0
b  Catherine    9.5
c     Cahill   16.5
d      James    NaN
e      Emily   11.0
f    Michael   20.0
g     Monica   17.0
h      Laura    NaN
i      Kevin    8.5
j     Jordan   19.0

In [164]:
df[['name','score']]

name  score
a  Anastasia   13.0
b  Catherine    9.5
c     Cahill   16.5
d      James    NaN
e      Emily   11.0
f    Michael   20.0
g     Monica   17.0
h      Laura    NaN
i      Kevin    8.5
j     Jordan   19.0

In [165]:
# Select First three reows of the DataFrame
df.iloc[:3]

attempts       name qualify  score
a         1  Anastasia     yes   13.0
b         3  Catherine      no    9.5
c         3     Cahill     yes   16.5

In [166]:
# Select 'name and 'score' columsn in rows 1,2,5,6 from the following data frame
df.iloc[[1,2,5,6], [1,3]]

name  score
b  Catherine    9.5
c     Cahill   16.5
f    Michael   20.0
g     Monica   17.0

In [168]:
# Select all columns whos attempts is larger than 2
df[df.attempts>2]

attempts       name qualify  score
b         3  Catherine      no    9.5
c         3     Cahill     yes   16.5
f         3    Michael     yes   20.0
h         3      Laura      no    NaN

In [169]:
# Select the rows where the score is missing(NaN)
df[df.isnull().any(axis = 1)]

attempts   name qualify  score
d         2  James      no    NaN
h         3  Laura      no    NaN

In [170]:
df[df['score'].isnull()]

attempts   name qualify  score
d         2  James      no    NaN
h         3  Laura      no    NaN

In [171]:
# Select the rows where number of attempts in the examinsation is less than 2 
# and score greater than 15
df[(df.attempts <=2) & (df.score > 15)]

attempts    name qualify  score
g         2  Monica     yes   17.0
j         1  Jordan     yes   19.0

In [177]:
# Calculate the sum of the examination attempts
df.attempts.sum()

22

In [178]:
# Calculate the mean of the score
df.score.mean()

14.3125

In [185]:
# Append a new row 'k' to DataFrame with the given values for each column
df[df['k']]

KeyError: 'k'